// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3w2vdXvazYyz6S8FHlYhJnXUuf2u5MOA',
    appId: '1:339661535820:web:811638313c113dba6b92e9',
    messagingSenderId: '339661535820',
    projectId: 'tlangau',
    authDomain: 'tlangau.firebaseapp.com',
    storageBucket: 'tlangau.firebasestorage.app',
    measurementId: 'G-BFHSQZCTRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpqmmAJIYr64YqgglDUJrrqvUAaZXRhE',
    appId: '1:339661535820:android:dd010d620d2071636b92e9',
    messagingSenderId: '339661535820',
    projectId: 'tlangau',
    storageBucket: 'tlangau.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWI5J-4oUN4g50vbPiD2ZSqN9Bv-FjGMA',
    appId: '1:339661535820:ios:fd2fe9e534ed71b16b92e9',
    messagingSenderId: '339661535820',
    projectId: 'tlangau',
    storageBucket: 'tlangau.firebasestorage.app',
    iosBundleId: 'com.example.tlangau',
  );
}
